# Generated by Django 4.2.22 on 2025-10-30 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0038_role_can_edit_global_keystore_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="role",
            name="can_use_registry",
            field=models.BooleanField(default=False),
        ),
    ]
